placement_diaries/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('student.urls')),
]

student/urls.py
from unicodedata import name
from django.urls import path,include
from . import views

app_name ='student'

urlpatterns=[
    path('login/',views.loginPage,name='login'),
    path('register/',views.registerPage,name='register'),
    path('',views.Index,name='index'),
    path('page/<int:postid>/',views.postView,name='posts'),
    path('logout/',views.logoutPage , name='logout'),
]

student/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now
# Create your models here.
class post(models.Model):

    title = models.CharField(max_length=100)
    text = models.TextField()
    is_verified = models.BooleanField(default=False)
    created_by = models.ForeignKey(User,on_delete=models.CASCADE)
    date_created = models.DateTimeField(default=now , editable=False)

    def __str__(self):
        return self.title

student/forms.py
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.forms import UserCreationForm


class loginForm(forms.ModelForm):
    model = User
    fields = ['username','password']


class UserCreation(UserCreationForm):
    
    class Meta:
        model = User
        fields = ['username' , 'email', 'password1', 'password2']

student/views.py
from django.shortcuts import render,redirect
from .forms import loginForm,UserCreation
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from .models import post
# Create your views here.

def loginPage(request):

    if request.method == "POST":
        username = request.POST.get('Username')
        password = request.POST.get('Password')

        user = authenticate(request , username = username,password = password)

        if user is not None :
            login(request,user)
            return redirect('/')
        else:
            messages.error(request , 'password / username is incorrect')

    return  render(request , 'student/login.html')

def logoutPage(request):
    logout(request)
    return redirect('/login')

def registerPage(request):

    if request.method == 'POST':
        form = UserCreation(request.POST)

        if form.is_valid:
            try:
                form.save()
                return redirect('/login')
            except:
                messages.error(request ,form.errors)
                return redirect('/register')
    else:
        form = UserCreation()

    return render(request,'student/register.html',{'form' : form,})


def Index(request):
    return render(request ,'student/index.html')


def postView(request, postid):
    posts = post.objects.filter(pk__lt = 10*postid ).filter(pk__gte = 10*(postid-1)).filter(is_verified = True)
    
    return render(request, 'student/postView.html',{'posts' : posts,'id' : postid+1,})

student/templates/student/base_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    {% endblock %}
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Rock+3D&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
        integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    {% load static %}
    <link rel="stylesheet" href="{% static 'student/base_template.css' %}">
</head>
<body>
    <div class="wrapper">
        <nav>
            <div class="container navbar-wrap">
                <div class="logo-nav">
                    <a href="">PES</a>
                </div>
                <div class="links_content">
                    <a href="#" style="color: #05386B;" class="mx-4">Contact</a>
                    {% if user.is_authenticated %}
                        <a href="{% url 'student:logout'%}" class="btn-violet btn-light">Logout</a>
                    {% else %}
                        <a href="{% url 'student:login' %}" class="btn-violet mx-3">Login</a>
                    {% endif %}

                </div>
            </div>
        </nav>
    </div>

    {% block body %}
    {% endblock %}


    <div class="footer-wrap">
        <div class="inner-wrap pt-4">

            <footer class="page-footer  pt-4">
                
                <div class="container">
    
                    <ul class="list-unstyled list-inline text-center">
                <li class="list-inline-item">
                    <a class="btn-floating btn-fb mx-1">
                        <i class="fab fa-facebook-f"> </i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a class="btn-floating btn-tw mx-1">
                        <i class="fab fa-twitter"> </i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a class="btn-floating btn-gplus mx-1">
                        <i class="fab fa-google-plus-g"> </i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a class="btn-floating btn-li mx-1">
                        <i class="fab fa-linkedin-in"> </i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a class="btn-floating btn-dribbble mx-1">
                        <i class="fab fa-dribbble"> </i>
                    </a>
                </li>
            </ul>
            
        </div>
        
        <div style="padding-left : 20px;">
            <svg width="56" height="54" viewBox="0 0 56 54" fill="none" xmlns="http://www.w3.org/2000/svg" id="mode-toggler">
                <path class="sun"
                d="M56 27C56 41.9117 43.464 54 28 54C12.536 54 0 41.9117 0 27C0 12.0883 12.536 0 28 0C43.464 0 56 12.0883 56 27Z"
                fill="#E6E16D" />
            </svg>
            <a href="{% url 'student:index' %}" id="toggle-btn" class="btn-violet mx-3" style="text-decoration: none;">Toggle</a>
        </div>
        
        <div class="footer-copyright text-center py-3">© 2022 Copyright:
            <a href="{% url 'student:index' %}" style="text-decoration : none;">PES.com</a>
        </div>
    </footer>
    </div>
</div>
    

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/3.2.1/anime.min.js"
        integrity="sha512-z4OUqw38qNLpn1libAN9BsoDx6nbNFio5lA6CuTp9NlK83b89hgyCVq+N5FdBJptINztxn1Z3SaKSKUS5UP60Q=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="{% static 'student/modetoggler.js' %}"></script>
</body>
</html>

student/templates/student/index.html
{% extends 'student/base_template.html' %}

{% block title %}
    <title>Home | user portal</title>

{% endblock %}

{% block body %}
    <div class="text-center" style="margin-top: 250px;">    
        <h1 style="color: #05386B;">Share Your Placement Experiences!!</h1>
    </div>
    <div style="display: flex; justify-content: center; margin-top: 60px; margin-bottom: 300px;">
        <a href="{% url 'student:posts' 1%}" class="btn-violet" style="text-decoration: none;">Explore </a>
    </div>
    <div class="line container"></div>
    <div class="container my-5" style="
            display: flex;
            justify-content: space-between;
            align-items: center;
    ">
        <iframe width="560" height="315" src="https://www.youtube.com/embed/wODg1AKuRc8" title="YouTube video player"
            frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
            allowfullscreen></iframe>
        <div style="width: 400px;">
            <div class="card" style="padding: 15px;">
                <h2 style="color:#05386B;">Thank you for using this website. Wishing you all the best in everything you do <3. </h2>
            </div>
        </div>
    </div>
{% endblock %}

student/templates/student/postView.html
{% extends 'student/base_template.html' %}

{% block title %}
    <title>POSTS | User portal</title>
{% endblock %}

{%block body%}

    {% if posts %}
        <div class="container my-5">
            {% for post in posts %}
                <div class="card my-5" style="padding: 20px;">
                    <h4 style="color: #05386B;" class="fw-bold">{{post.title}}</h4>
                    <p>{{post.text}}</p>
                    <div style="display: flex;justify-content: flex-start;">
                        {{post.created_by}},
                        {{post.date_created}} PT
                    </div>
                </div>
            {% endfor %}
        </div>
        <div style="display: flex; justify-content: flex-end; margin-bottom: 40px; padding-right: 20px;">
            <a href="{% url 'student:posts' id%}" class="btn-violet" style="text-decoration: none;">Next Page</a>
        </div>
    {% else %}
        <div style="color: #05386B;" class="text-center my-5">
            <h1>That's all we have for now to show !!!!</h1>
        </div>
    {% endif %}

    
{%endblock %}